name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend_flask:
    name: Backend (Flask)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint Python code
      - name: Lint Python code
        run: echo "Skipping lint for now"

      # Step 5: Run Python tests
      - name: Run Python tests
        run: |
          if [ -f test_app.py ]; then python -m unittest test_app.py; else echo "No tests found."; fi


  deploy:
    name: Deploy & Push to Docker Hub
    needs: [backend_flask]
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t saisathvikapotluri/backend_flask:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push saisathvikapotluri/backend_flask:latest
